version: '3.9'  
volumes:
    AnimesControlDb

services:
  db_postgres: 
    image: postgres
    container_name: animesdb-container
    ports:
      - 5432:5432
    restart: always
    volumes:
      - AnimesControlDb:/var/lib/postgres
    environment: 
      POSTGRES_USER: mathemac
      POSTGRES_PASSWORD: mathemac
  
  api: 
    depends_on: db_postgres
    build: 
      dockerfile: dockerfile
      context: .
    ports: 8000:80
    environment: 
      DB_CONNECTION_STRING: "host=db_postgres;port=5432;database=animedatabase;username=mathemac;password=mathemac"


